# ==========================================
# VARIABLES GLOBALES
# Pega tu token aquí SIN comillas cuando expire
# ==========================================
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkY2JvdXRyb3M2NjZAZ21haWwuY29tIiwiY2xpbmljYUlkIjoiMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlN1cGVyQWRtaW4iLCJleHAiOjE3NzY0MjY0NTEsImlzcyI6Ik1lZGlDb3JlQVBJIiwiYXVkIjoiTWVkaUNvcmVDbGllbnRzIn0.iEExfWr4K5jpgArE2H7P8Fx7pdEIx_0pR8ih3RtY8xY


### 1. Iniciar sesión para obtener tu Token fresco (Solo úsalo cuando el de arriba expire)
POST https://localhost:7086/api/Auth/login
Content-Type: application/json

{
  "correo": "dcboutros666@gmail.com",
  "password": "cheetodebolita"
}

### ==========================================
### MÓDULO: PACIENTES
### ==========================================

### 2. Registrar un nuevo Paciente
POST https://localhost:7086/api/Pacientes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombreCompleto": "Juan Pérez",
  "telefono": "4421234567"
}

### 3. Consultar la lista de Pacientes de tu clínica
GET https://localhost:7086/api/Pacientes
Authorization: Bearer {{token}}

### Prueba de Paginación: Pedir la página 1, pero de tamaño 1
GET https://localhost:7086/api/Pacientes?pagina=1&recordsPorPagina=1
Authorization: Bearer {{token}}

### Nivel 3: Prueba de Caída de Servidor
GET https://localhost:7086/api/Pacientes/simular-caida
Authorization: Bearer {{token}}

### 1. Borrado Lógico de Juan Pérez (Ahora SÍ eres SuperAdmin)
DELETE https://localhost:7086/api/Pacientes/1
Authorization: Bearer {{token}}

### Intento de Hackeo: Registrar paciente con datos basura
POST https://localhost:7086/api/Pacientes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombreCompleto": "",
  "telefono": "123"
}

### ==========================================
### MÓDULO: CITAS MÉDICAS
### ==========================================

### 5. Agendar una Cita Médica (Paciente Juan)
POST https://localhost:7086/api/Citas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pacienteId": 4,
  "fechaHora": "2026-04-15T10:30:00",
  "motivoConsulta": "Dolor de cabeza severo y fiebre"
}

### 10. Agendamos a otra paciente (María) - Mismo ID de paciente 1 por rapidez
POST https://localhost:7086/api/Citas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pacienteId": 4,
  "fechaHora": "2026-04-16T12:00:00",
  "motivoConsulta": "Limpieza Dental"
}

### 6. Ver la agenda de la clínica
GET https://localhost:7086/api/Citas
Authorization: Bearer {{token}}

### 7. El Doctor termina la consulta de Juan Pérez (Cita ID 1) y le cobra $850.00
POST https://localhost:7086/api/Citas/1/completar
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "monto": 850.00
}

### 11. Terminamos la cita de María y le cobramos $500.00
POST https://localhost:7086/api/Citas/2/completar
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "monto": 500.00
}

### ==========================================
### MÓDULO: COBROS Y REPORTES
### ==========================================

### 8. La Recepcionista revisa quién falta de pagar hoy
GET https://localhost:7086/api/Cobros/pendientes
Authorization: Bearer {{token}}

### 9. Juan Pérez paga en la terminal y Recepción registra el pago (Cobro ID 1)
POST https://localhost:7086/api/Cobros/1/pagar
Content-Type: application/json
Authorization: Bearer {{token}}

### 12. Recepción registra el pago de María (Cobro ID 2)
POST https://localhost:7086/api/Cobros/2/pagar
Content-Type: application/json
Authorization: Bearer {{token}}

### 13. ¡EL REPORTE FINAL DE GERENCIA!
GET https://localhost:7086/api/Reportes/ingresos-acumulados
Authorization: Bearer {{token}}