### 1. Iniciar Sesión (Obtener el Token)
POST https://localhost:7086/api/Auth/login
Content-Type: application/json

{
  "correo": "dcboutros666@gmail.com",
  "password": "cheetodebolita"
}

### 2. Acceder a la Zona VIP
# Copia el token que te devolvió el paso 1 y pégalo abajo, 
# justo después de la palabra "Bearer " (deja un espacio).
GET https://localhost:7086/api/Auth/perfil-vip
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkY2JvdXRyb3M2NjZAZ21haWwuY29tIiwiY2xpbmljYUlkIjoiMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzc1NTY0MTI2LCJpc3MiOiJNZWRpQ29yZUFQSSIsImF1ZCI6Ik1lZGlDb3JlQ2xpZW50cyJ9.FYgEkMhb7qLTisWDwZeFsk0Q1P-94jEyPCUE0pzjI9M